name: Build and Test

on: [push]

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Modify version number
        uses: mingjun97/file-regex-replace@v1
        with:
          regex: \.0\<\/Version\>
          replacement: ".${{github.run_number}}</Version>"
          flags: "g"                  # Optional, defaults to "g"
          include: 'RedBear\.Auth\.ServiceClient\.csproj'    # Optional, defaults to ".*"
          path: 'src\RedBear.Auth.ServiceClient\'                   # Optional, defaults to '.'
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'
      - name: Install dependencies
        run: dotnet restore src/RedBear.Auth.ServiceClient.sln
      - name: Build
        run: dotnet build src/RedBear.Auth.ServiceClient.sln --configuration Release --no-restore
      - name: Publish the package
        if: github.ref == 'refs/heads/master'
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate